### ISSUE TITLE
Walking seems to no longer work for some reason

### ISSUE THREAD

**Issue by Bluscream** [lolo45654/altoclef#6]
https://paste.ee/p/We6Ca

**Comment by Bluscream** [comment]
Maybe this has something to do with it
```
[07:30:29] [pool-4-thread-2/ERROR]: Uncaught exception in thread "pool-4-thread-2"
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_19538()" because the return value of "baritone.api.utils.IPlayerContext.player()" is null
	at baritone.api.utils.IPlayerContext.playerFeet(IPlayerContext.java:61) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.cache.CachedWorld.guessPosition(CachedWorld.java:215) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.cache.CachedWorld.prune(CachedWorld.java:191) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.cache.CachedWorld.save(CachedWorld.java:181) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at baritone.cache.CachedWorld.lambda$new$0(CachedWorld.java:96) ~[baritone-1.18-SNAPSHOT-98b3823201e5a8a9.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Bluscream** [comment]
The problem was [Immersive Portals](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-mod)

**Comment by Bluscream** [comment]
Re-opening because of https://github.com/qouteall/ImmersivePortalsMod/issues/933#issuecomment-997566918
